[project]
authors = ["Til"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pixi-jobarray"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.0,<4"
numpy = ">=2.1.3,<3"
scipy = ">=1.14.1,<2"
astropy = ">=6.1.4,<7"
pip = ">=24.3.1,<25"
h5py = ">=3.12.1,<4"
ipython = ">=8.29.0,<9"
jupyter = ">=1.1.1,<2"
dill = ">=0.3.9,<0.4"
matplotlib = ">=3.9.2,<4"
tqdm = ">=4.66.6,<5"
pixi-kernel = ">=0.5.1,<0.6"
ipykernel = ">=6.29.5,<7"
click = ">=8.1.7,<9"

[pypi-dependencies]
dustpy = ">=1.0.6, <2"
